### ISSUE TITLE
peer not working?

### ISSUE THREAD

**Issue by nilford** [stratosnet/stratos-chain-testnet#13]
after starting the node, synchronization does not occur. in the service logs this:
E[2022-02-12|21:01:57.200] Stopping peer for error                      module=p2p peer="Peer{MConn{3.128.151.132:26656} 03c7cf4acca06a48431f29782c398ae0eba6cd8c out}" err=EOF

**Comment by espoir1989** [comment]
me too

**Comment by Preflyt** [comment]
Same
