### ISSUE TITLE
HEAD is now at 9fed18d Merge pull request #31 from stratosnet/release

### ISSUE THREAD

**Issue by b1shop** [stratosnet/stratos-chain-testnet#3]
Hi guys,

following testnet installation guide and get this message on "git chekout v0.3.0" command "HEAD is now at 9fed18d Merge pull request #31 from stratosnet/release" what i need to do here?

**Comment by alexstratos** [comment]
after` git checkout v0.3.0`, just run `make build` and build the binary,  the stchaind/stchaincli binary will be under ./build folder

**Comment by b1shop** [comment]
I’ve tried but folder is empty
