### ISSUE TITLE
Faucet 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by proftechrus** [stratosnet/stratos-chain-testnet#5]
**second faucet to the same address**

 curl -X POST https://faucet-test.thestratos.org/faucet/st1jgmrcfdpg8tkynv9djyc4wese0kp3f2pxa062g

**gives the message:**

`
<title>503 Service Temporarily Unavailable</title>
<center><h1>503 Service Temporarily Unavailable</h1></center>
nginx/1.18.0 (Ubuntu)
`

**is this normal behavior?**

**Comment by alexstratos** [comment]
there  was a configuration issue on the nginx proxy we had for all services, it has been fixed. @proftechrus
