### ISSUE TITLE
After a wallet is created - its address is not recognized

### ISSUE THREAD

**Issue by proftechrus** [stratosnet/stratos-chain-testnet#6]
**Command:**
./stchaincli query account st1s44z52raf06ny3h9qnkq2arfy7h683kx500l3t --home ./
ERROR: unknown address: account st1s44z52raf06ny3h9qnkq2arfy7h683kx500l3t does not exist

**Command:**
./stchaincli query account st1jgmrcfdpg8tkynv9djyc4wese0kp3f2pxa062g --home ./
ERROR: unknown address: account st1jgmrcfdpg8tkynv9djyc4wese0kp3f2pxa062g does not exist

**Command:**
./stchaincli tx send st1s44z52raf06ny3h9qnkq2arfy7h683kx500l3t st1jgmrcfdpg8tkynv9djyc4wese0kp3f2pxa062g 666 --home ./ --keyring-backend test --chain-id test-chain-1
failed to get from fields: The specified item could not be found in the keyring

please help

**Comment by dannyfund** [comment]
unknown address  Just wait for the block synchronization to complete.

**Comment by alexstratos** [comment]
@proftechrus you can join our discord to have better/quicker answer for question like this.
